config/routes.rb
ShoppingMania::Application.routes.draw do
  get "auth/facebook/callback" => "sessions#create"

  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:index, :destroy] do
    collection do
      get "activate" => "users#activate"
      get "reset_password" => "users#reset_password"
      post "reset_password" => "users#send_password_token"
      put "reset_password" => "users#update_password"

      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
      resources :carts, only: :show
      resources :orders, only: [:index, :new, :create, :show]
      resources :wishlists, only: [:index, :create, :destroy]
    end
  end

  resources :items do
    collection do
      put "admin/edit" => "items#admin_shortcut"
    end

    resources :cart_items, only: :create
    resources :saved_items, only: :create
    resources :wishlist_items, only: :create
    resources :reviews, only: :create
  end

  resources :cart_items, only: [:update, :destroy]
  resources :saved_items, only: :destroy
  resources :wishlist_items, only: :destroy
  resources :photos, only: :destroy

  root to: "items#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :uid, :first_name, :last_name, :email, :password, :password_confirmation

  validates :first_name, :last_name, :email, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }, uniqueness: true

  has_many :tokens
  has_one :cart, inverse_of: :user
  has_many :orders, include: :order_items, order: "created_at DESC"
  has_many :wishlists, include: :wishlist_items
  has_many :addresses
  has_many :saved_items

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email);

    (user && user.authenticate(password)) ? user : nil
  end

  def self.create_from_fb_data(params)
    user = User.find_by_email(params[:info][:email])
    if user
      user.uid = params[:uid]
    else
      user = User.create(
        uid: params[:uid],
        first_name: params[:info][:first_name],
        last_name: params[:info][:last_name],
        email: params[:info][:email],
        password: SecureRandom::urlsafe_base64(8)
      )
    end
    user.activated = true
    user.save!

    user
  end

  def activated?
    activated
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    is_admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.cart = Cart.build_temporary_cart(
      session[:cart_item_params],
      session[:saved_item_ids]
    )

    if @user.save
      UserMailer.welcome_email(@user).deliver!
      flash[:notice] = "Please check your email to activate your account"
      session[:cart_item_params] = nil
      session[:saved_item_ids] = nil
      redirect_to new_session_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if params[:id].to_i == current_user.id
      @user = current_user
      render :show
    else
      redirect_to user_url(current_user)
    end
  end

  def edit
    @user = current_user
  end

  def update
    filter_user_password_params(params)
    @user = current_user

    if params[:user][:password]
      update_status = @user.authenticate(params[:old_password]) &&
        @user.update_attributes(params[:user])
    else
      update_status = @user.update_attributes(params[:user])
    end

    if update_status
      flash[:notice] = "Successfully updated"
      redirect_to edit_user_url(@user)
    else
      flash[:errors] = "Could not update user information"
      render :edit
    end
  end

  def activate
    token = Token.find_by_token_string(params[:activation_token])
    token.destroy

    user = token.user
    user.activated = true
    user.save!
    sign_in(user)

    redirect_to root_url
  end

  def reset_password
    if params[:password_reset_token]
      render :reset_password
    else
      render :request_token
    end
  end

  def send_password_token
    user = User.find_by_email(params[:user][:email])
    if user
      UserMailer.password_reset_email(user).deliver!
      flash[:notice] = "Please check your email for the link to reset your password"
      redirect_to new_session_url
    else
      flash[:error] = "Could not find the user with given email"
      redirect_to :back
    end
  end

  def update_password
    token = Token.find_by_token_string(params[:password_reset_token])
    user = token.user
    if user.update_attributes(params[:user])
      flash[:notice] = "You have successfully changed your password"
      token.destroy
      sign_in(user)
      redirect_to root_url
    else
      flash[:errors] = user.errors.full_messages
      render :reset_password
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_input_fields.html.erb
<%= auth_token %>

<div class="input">
  <label for="user_first_name">First Name:</label>
  <input type="text" id="user_first_name"
    name="user[first_name]" value="<%= user.first_name %>">
</div>

<div class="input">
  <label for="user_last_name">Last Name:</label>
  <input type="text" id="user_last_name"
    name="user[last_name]" value="<%= user.last_name %>">
</div>

<div class="input">
  <label for="user_email">Email:</label>
  <input type="email" id="user_email"
    name="user[email]" value="<%= user.email %>">
</div>

<div class="input">
  <label for="user_password">Password:</label>
  <input type="password" id="user_password"
    name="user[password]">
</div>

<div class="input">
  <label for="user_password_confirmation">Confirm Password:</label>
  <input type="password" id="user_password_confirmation"
    name="user[password_confirmation]">
</div>

app/views/users/edit.html.erb
<form action="<%= user_url(@user) %>" method="post" class="user-form">
  <h3>Edit Information</h3>

  <%= render partial: "input_fields", locals: { user: @user } %>

  <div class="input">
    <label for="user_old_password">Old Password:</label>
    <input type="password" id="user_old_password"
      name="old_password">
  </div>

  <input type="hidden" name="_method" value="put">

  <% flash[:errors].try(:each) do |error| %>
    <label class="error"><%= error %></label>
  <% end %>

  <% if flash[:notice] %>
    <label class="notice"><%= flash[:notice] %></label>
  <% end %>

  <div class="submit">
    <input type="submit" value="Update information">
  </div>
</form>

app/views/users/new.html.erb
<form class="user-form" action="<%= users_url %>" method="post">
  <h3>Create New Account</h3>
  <%= render partial: "input_fields", locals: { user: @user } %>

  <% flash[:errors].try(:each) do |error| %>
    <p class="error"><%= error %></p>
  <% end %>

  <div class="submit">
    <input type="submit" value="Sign up">
  </div>
</form>

app/views/users/request_token.html.erb
<form class="user-form" action="<%= reset_password_users_url %>" method="post">
  <%= auth_token %>

  <h3>Reset password</h3>

  <div class="input">
    <label for="user_email">Email:</label>
    <input type="email" id="user_email"
      name="user[email]">
  </div>

  <div class="submit">
    <input type="submit" value="Send email">
  </div>
</form>

app/views/users/reset_password.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <label class="error"><%= error %></label>
  <% end %>
<% end %>

<form class="user-form" action="<%= reset_password_users_url %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="_method" value="put">
  <input type="hidden" name="password_reset_token"
    value="<%= params[:password_reset_token] %>">

  <h3>Reset password</h3>

  <div class="input">
    <label for="user_password">Password:</label>
    <input type="password" id="user_password"
      name="user[password]">
  </div>

  <div class="input">
    <label for="user_password_confirmation">Confirm Password:</label>
    <input type="password" id="user_password_confirmation"
      name="user[password_confirmation]">
  </div>

  <div class="submit">
    <input type="submit" value="Update password">
  </div>
</form>

app/views/users/show.html.erb
<section class="account-control">
  <ul>
    <li><%= link_to "Edit Information", edit_user_url(@user) %></li>
    <li><%= link_to "Manage Address Book", addresses_url %></li>
    <li><%= link_to "View Your Orders", orders_url %></li>
    <li><%= link_to "View Wishlists", wishlists_url %></li>
  </ul>
</section>