config/routes.rb
ShoppingMania::Application.routes.draw do
  get "auth/facebook/callback" => "sessions#create"

  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:index, :destroy] do
    collection do
      get "activate" => "users#activate"
      get "reset_password" => "users#reset_password"
      post "reset_password" => "users#send_password_token"
      put "reset_password" => "users#update_password"

      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
      resources :carts, only: :show
      resources :orders, only: [:index, :new, :create, :show]
      resources :wishlists, only: [:index, :create, :destroy]
    end
  end

  resources :items do
    collection do
      put "admin/edit" => "items#admin_shortcut"
    end

    resources :cart_items, only: :create
    resources :saved_items, only: :create
    resources :wishlist_items, only: :create
    resources :reviews, only: :create
  end

  resources :cart_items, only: [:update, :destroy]
  resources :saved_items, only: :destroy
  resources :wishlist_items, only: :destroy
  resources :photos, only: :destroy

  root to: "items#index"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :user_id

  validates :user, presence: true
  belongs_to :user
  has_many :cart_items, dependent: :destroy, inverse_of: :cart
  has_many :saved_items, dependent: :destroy, inverse_of: :cart

  def self.build_temporary_cart(cart_item_params, saved_item_ids = [])
    cart = Cart.new

    cart_item_params.try(:each) do |item_id, quantity|
      cart_item = CartItem.new(item_id: item_id, quantity: quantity.to_i)
      cart.cart_items << cart_item
    end

    saved_item_ids.try(:each) do |item_id|
      saved_item = SavedItem.new(item_id: item_id)
      cart.saved_items << saved_item
    end

    cart
  end

  def add_item(item_id, quantity)
    raise "must add a positive quantity" unless quantity > 0

    cart_item = CartItem.find_by_cart_id_and_item_id(id, item_id)

    if cart_item
      new_quantity = cart_item.quantity + quantity
      cart_item.update_attributes(quantity: new_quantity)
    else
      cart_items.create(item_id: item_id, quantity: quantity)
      saved_item = SavedItem.find_by_cart_id_and_item_id(id, item_id)
      saved_item.try(:destroy)
    end
  end

  def save_item(item_id, remove_from_cart = true)
    saved_item = SavedItem.find_by_cart_id_and_item_id(id, item_id)
    saved_items.create(item_id: item_id) unless saved_item
    if remove_from_cart
      cart_item = CartItem.find_by_cart_id_and_item_id(id, item_id)
      cart_item.try(:destroy)
    end
  end

  def total
    if persisted?
      cart_items.includes(:item).map(&:subtotal).inject(:+)
    else
      item_ids = cart_items.map(&:item_id)
      items_hash = {}
      Item.find(item_ids).each { |item| items_hash[item.id] = item }

      cart_items.each do |cart_item|
        cart_item.item = items_hash[cart_item.item_id]
      end
      cart_items.map(&:subtotal).inject(:+)
    end
  end

  def combine(another_cart)
    return self if user_id && another_cart.user_id

    self.user_id ||= another_cart.user_id
    save!

    another_cart.cart_items.each do |cart_item|
      add_item(cart_item.item_id, cart_item.quantity)
    end

    another_cart.saved_items.each do |saved_item|
      save_item(saved_item.item_id, false)
    end

    another_cart.destroy

    self
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    if current_user
      @cart =  current_user.cart
    else
      @cart = Cart.build_temporary_cart(session[:cart_item_params], session[:saved_item_ids])
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<section class="cart group">
  <div class="status-messages">
    <%= status_messages %>
  </div>

  <% if @cart.cart_items.empty? %>
    <p>There are no items in your cart.</p>
  <% else %>
    <table>
      <thead>
        <th class="name">Name</th>
        <th class="currency">Price</th>
        <th class="quantity">Quantity</th>
        <th class="currency">Total</th>
      </thead>

      <tfoot>
        <tr>
          <td colspan="3" class="currency">Grand Total:</td>
          <td class="currency total">$<%= @cart.total %></td>
        </tr>
      </tfoot>

      <tbody>
        <% @cart.cart_items.each do |cart_item| %>
        <tr>
          <td class="name">
            <img src="<%= cart_item.item.thumbnail %>">
            <%= link_to cart_item.item.name, item_url(cart_item.item) %>
            <%= button_to "Save for later", item_saved_items_url(cart_item.item) %>
          </td>
          <td class="currency">$<%= cart_item.item.price %></td>
          <td class="quantity group"><%= render partial: "cart_items/form", locals: { cart_item: cart_item } %></td>
          <td class="currency subtotal">$<%= cart_item.subtotal%></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="button group">
      <%= link_to "Checkout", new_order_url %>
    </div>

  <% end %>

  <% unless @cart.saved_items.empty? %>
    <h3>Saved Items</h3>

    <section class="saved group">
      <ul>
        <% @cart.saved_items.each do |saved_item| %>
          <li>
            <img src="<%= saved_item.item.thumbnail %>">
            <%= link_to saved_item.item.name, item_url(saved_item.item) %>
            <p>$<%= saved_item.item.price %></p>
            <div class="group">
              <form action="<%= item_cart_items_url(saved_item.item) %>" method="post">
                <%= auth_token %>
                <input type="hidden" name="cart_item[quantity]" value="1">

                <input type="submit" value="Move to Cart">
              </form>
              <%= button_to "Remove", saved_item_url(saved_item.id || saved_item.item_id), method: :delete %>
            </div>
          </li>
        <% end %>
      </ul>
    </section>
  <% end %>
</section>

<script>
$(document).ready(function () {
  $(".update").on("ajax:success", function(event, data){
    $(".status-messages").html(data.status_messages);
    $(this).find("input[type='number']").val(data.quantity);
    $(this).closest("tr").find(".subtotal").html("$" + data.subtotal);
    $(".total").html("$" + data.total);
  });

  $(".remove").on("ajax:success", function(event, data){
    if (data["total"] > 0) {
      $(event.target).closest("tr").remove();
      $(".total").html("$" + data["total"]);
    } else {
      location.reload();
    }
  });
});
</script>