config/routes.rb
ShoppingMania::Application.routes.draw do
  get "auth/facebook/callback" => "sessions#create"

  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:index, :destroy] do
    collection do
      get "activate" => "users#activate"
      get "reset_password" => "users#reset_password"
      post "reset_password" => "users#send_password_token"
      put "reset_password" => "users#update_password"

      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
      resources :carts, only: :show
      resources :orders, only: [:index, :new, :create, :show]
      resources :wishlists, only: [:index, :create, :destroy]
    end
  end

  resources :items do
    collection do
      put "admin/edit" => "items#admin_shortcut"
    end

    resources :cart_items, only: :create
    resources :saved_items, only: :create
    resources :wishlist_items, only: :create
    resources :reviews, only: :create
  end

  resources :cart_items, only: [:update, :destroy]
  resources :saved_items, only: :destroy
  resources :wishlist_items, only: :destroy
  resources :photos, only: :destroy

  root to: "items#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  include PgSearch
  pg_search_scope(
    :search_by_name,
    against: :name,
    using: {
      tsearch: {
        prefix: true,
        dictionary: "english"
      }
    }
  )

  attr_accessible :name, :price, :stock, :brand_id, :category_id, :description

  validates :name, :price, :stock, :brand, :category, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :stock, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0 }

  belongs_to :brand
  belongs_to :category
  has_many :photos, dependent: :destroy, inverse_of: :item
  has_many :reviews

  def self.filter(options)
    items = Item.includes(:photos)
              .joins("LEFT OUTER JOIN reviews ON items.id = reviews.item_id")
              .group("items.id")
              .select("items.*, AVG(reviews.rating) AS rating")

    return items if (options.nil? || options.empty?)

    items = Item.filter_by_price(items, options[:price]) if options[:price]
    items = Item.filter_by_brand(items, options[:brand_ids]) if options[:brand_ids]
    items = Item.filter_by_category(items, options[:category_ids]) if options[:category_ids]
    items = Item.filter_by_rating(items, options[:rating]) if options[:rating]
    items = items.search_by_name(options[:name]) if options[:name]

    items
  end

  def self.filter_by_price(items, options)
    min_price = options[:min] || 0
    max_price = options[:max] || 0

    items = items.where("items.price >= ?", min_price) if min_price > 0
    items = items.where("items.price <= ?", max_price) if max_price > 0

    items
  end

  def self.filter_by_brand(items, brand_ids)
    return items if brand_ids.empty?

    items.where("brand_id IN (?)", brand_ids)
  end

  def self.filter_by_category(items, category_ids)
    return items if category_ids.empty?

    items.where("category_id IN (?)", category_ids)
  end

  def self.filter_by_rating(items, min_rating)
    return items if min_rating > 5

    items.having("AVG(reviews.rating) >= ?", min_rating)
  end

  def self.sort(items, criterium)
    case criterium
    when "price_asc"
      items.order("price")
    when "price_desc"
      items.order("price").reverse_order
    when "recent"
      items.order("items.created_at").reverse_order
    when "rating"
      items.order("AVG(reviews.rating) DESC NULLS LAST")
    when "popularity"
      items.joins("LEFT OUTER JOIN order_items ON items.id = order_items.item_id")
        .group("items.id")
        .order("SUM(order_items.quantity) DESC NULLS LAST")
    else
      items.order("items.updated_at")
    end
  end

  def thumbnail
    photos.first.image.url(:thumb)
  end

  def average_rating
    Rails.cache.fetch("average_rating_item#{self.id}", :expires_in => 1.hour) do
      force_average_rating
    end
  end

  def force_average_rating
    self.reviews.average("rating").to_f.round(1)
  end

  def add_stock!(quantity)
    raise "must add positive stock" if quantity < 1

    self.stock += quantity
    self.save!
  end

  def remove_stock!(quantity)
    raise "must remove positive stock" if quantity < 1
    raise "not enough stock" if quantity > stock

    self.stock -= quantity
    self.save!
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :require_admin!, except: [:index, :show]

  #chosen js plug-in for searchbox
  def index
    parse_filter_params if params[:filter]

    items = Item.filter(params[:filter])
    @items = Item.sort(items, params[:sort]).page(params[:page])

    if request.xhr?
      render partial: "items", locals: { items: @items }, layout: false
    else
      render :index
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params[:item])
    photo_params = params[:photos].values
    @item.photos.new(photo_params)

    if @item.save
      flash[:notice] = "New item has been added"
      redirect_to item_url(@item)
    else
      flash[:errors] = @item.errors.full_messages
      render :new
    end
  end

  def show
    @item = Item.includes(:photos).find(params[:id])
    @photo = @item.photos.first
    @wishlists = current_user.try(:wishlists)
    @item_rating = @item.average_rating
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if params[:photos]
      @item.photos.new([params[:photos]])
    end

    if @item.update_attributes(params[:item])
      flash[:notice] = "Item has been successfully updated"
      redirect_to edit_item_url(@item)
    else
      flash[:errors] = @item.errors.full_messages
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to user_url(current_user)
  end

  def admin_shortcut
    if params[:item_id].empty?
      redirect_to edit_item_url(Item.first)
    else
      redirect_to edit_item_url(params[:item_id])
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_add_item_form.html.erb
<form action="<%= item_cart_items_url(item) %>" method="post">
  <%= flash[:errors] if flash[:errors] %>
  <%= flash[:notice] if flash[:notice] %><br>

  <%= auth_token %>

  <label for="cart_item_quantity">Quantity</label>
  <input type="number" id="cart_item_quantity" name="cart_item[quantity]">

  <br>

  <input type="submit" value="Add to Cart">
</form>

app/views/items/_add_items_form.html.erb
<form action="<%= item_cart_items_url(item) %>" method="post">
  <%= flash[:errors] if flash[:errors] %>
  <%= flash[:notice] if flash[:notice] %><br>

  <%= auth_token %>

  <label for="cart_item_quantity">Quantity</label>
  <input type="number" id="cart_item_quantity" name="cart_item[quantity]">

  <br>

  <input type="submit" value="Add to Cart">
</form>

app/views/items/_admin_search_form.html.erb
<form action="<%= admin_edit_items_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="put">
  <label for="item_id">Item ID:</label>
  <input type="text" name="item_id" id="item_id">
  <input type="submit" value="Edit Item">
</form>

app/views/items/_filter_items_form.html.erb
<form action="<%= items_url %>" method="get" data-remote="true" class="filter-form">
  <div class="button">
    <input type="submit" value="Search">
  </div>

  <div class="criteria">
    <label for="sort_criterium">Sort by</label>
    <select id="sort_criterium" name="sort">
      <option value="price_asc" <%= "selected" if params[:sort] == "price_asc" %>>
        Price: Low to High</option>
      <option value="price_desc" <%= "selected" if params[:sort] == "price_desc" %>>
        Price: High to Low</option>
      <option value="recent" <%= "selected" if params[:sort] == "recent" %>>
        Most recent</option>
      <option value="rating" <%= "selected" if params[:sort] == "rating" %>>
        Highest rating</option>
      <option value="popularity" <%= "selected" if params[:sort] == "popularity" %>>
        Most popular</option>
    </select>
  </div>

  <div class="criteria input">
    <label for="filter_name">Name</label>
    <input type="text" name="filter[name]" id="filter_name" value="<%= filter[:name] %>"><br>
  </div>

  <div class="criteria choose">
    <p>Price</p>
    <label for="filter_min_price">$</label>
    <input type="text" name="filter[price][min]" id="filter_min_price"
      value="<%= filter[:price][:min] if filter[:price] %>">
    <span> to </span>
    <label for="filter_max_price">$</label>
    <input type="text" name="filter[price][max]" id="filter_max_price"
      value="<%= filter[:price][:max] if filter[:price] %>">
  </div>

  <div class="criteria">
    <label>Brands</label>
    <ul>
    <% brands.each do |brand| %>
      <li>
        <input type="checkbox"
          name="filter[brand_ids][]"
          value="<%= brand.id %>"
          id="brand_<%= brand.id %>"
          <%= "checked" if filter[:brand_ids] && filter[:brand_ids].include?(brand.id) %>>
        <label for="brand_<%= brand.id %>"><%= brand.name %></label>
      </li>
    <% end %>
    </ul>
  </div>

  <div class="criteria">
    <label>Categories</label>
    <ul>
    <% categories.each do |category| %>
      <li>
        <input type="checkbox"
          name="filter[category_ids][]"
          value="<%= category.id %>"
          id="category_<%= category.id %>"
          <%= "checked" if filter[:category_ids] && filter[:category_ids].include?(category.id) %>>
        <label for="category_<%= category.id %>"><%= category.name %></label>
      </li>
    <% end %>
    </ul>
  </div>

  <div class="criteria">
    <label for="filter_rating">Minimum Rating</label>
    <select id="filter_rating" name="filter[rating]">
      <% 4.downto(2).each do |rating| %>
        <option value="<%= rating %>" <%= "selected" if filter[:rating] == rating %>><%= rating %></option>
      <% end %>
      <option <%= "selected" unless filter[:rating]%>></option>
    </select>
  </div>
</form>

app/views/items/_item_fields.html.erb
<%= auth_token %>

<div class="input">
  <label for="item_photos">Add Photos</label>
  <ul class="photo-upload-list">
    <li><input type="file" name="photos[0][image]"></li>
  </ul>
</div>

<div class="input">
  <label for="item_name">Name:</label>
  <input type="text" id="item_name" name="item[name]" value="<%= item.name %>">
</div>

<div class="input">
  <label for="item_price">Price:</label>
  <input type="text" id="item_price" name="item[price]" value="<%= item.price %>">
</div>

<div class="input">
  <label for="item_stock">Stock:</label>
  <input type="text" id="item_stock" name="item[stock]" value="<%= item.stock %>">
</div>

<div class="input">
  <label for="item_description">Description:</label>
  <textarea id="item_description" name="item[description]"><%= item.description %></textarea>
</div>

<div class="input">
  <label for="item_brand">Brand:</label>
  <select id="item_brand" name="item[brand_id]">
    <option value=""></option>
    <% Brand.all.each do |brand| %>
    <option value="<%= brand.id %>"
      <%= "selected" if brand.id == item.brand_id %>><%= brand.name %></option>
    <% end %>
  </select>
</div>

<div class="input">
  <label for="item_category">Category:</label>
  <select id="item_category" name="item[category_id]">
    <option value=""></option>
    <% Category.all.each do |category| %>
    <option value="<%= category.id %>"
      <%= "selected" if category.id == item.category_id %>><%= category.name %></option>
    <% end %>
  </select>
</div>

app/views/items/_item_summary.html.erb
<div class="item">
  <a href="<%= item_url(item) %>">
    <img src="<%= item.thumbnail %>">
  </a>
  <div class="summary">
    <%= link_to item.name, item_url(item) %>
    <p>Price: $<%= item.price %></p>

    <% rating = item.rating.to_f.round(1) %>
    <% if rating >= 1%>
      <p>Rating: <%= rating %></p>
    <% else %>
      <p>Rating: Not rated yet</p>
    <% end %>

    <% if item.stock == 0 %>
      <p class="error">Out of Stock</p>
    <% end %>
  </div>
</div>

app/views/items/_items.html.erb
<% if items.length == 0 %>
  <p>There are no items to display</p>
<% else %>
  <nav class="page-nav-bar group">
    <%= paginate items %>
  </nav>

  <ul class="group">
  <% items.each do |item| %>
    <li>
      <%= render partial: "item_summary", locals: { item: item } %>
    </li>
  <% end %>
  </ul>

  <nav class="page-nav-bar group">
    <%= paginate items %>
  </nav>
<% end %>

app/views/items/_status_messages.html.erb
<% if flash[:error] %>
  <p class="error"><%= flash[:error] %></p>
<% end %>

<%if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

app/views/items/edit.html.erb
<section class="item-form group">
  <ul>
    <% @item.photos.each do |photo| %>
      <li class="group">
        <img src="<%= photo.image.url(:thumb) %>">
        <%= button_to "Remove Photo", photo_url(photo),
          method: :delete, form_class: "remove-item" %>
      </li>
    <% end %>
  </ul>

  <form action="<%= item_url(@item) %>" method="post" enctype="multipart/form-data">

    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>

    <% flash[:errors].try(:each) do |error| %>
      <p class="error"><%= error %></p>
    <% end %>

    <input type="hidden" name="_method" value="put">

    <%= render partial:"item_fields", locals: { item: @item } %>

    <div class="submit">
      <input type="submit" value="Update Item">
    </div>
  </form>

  <%= button_to "Delete Item", item_url(@item), method: :delete, form_class: "remove-item" %>

</section>

app/views/items/index.html.erb
<section class="main group">
  <section class="sidebar">
    <%= render partial: "filter_items_form",
      locals: { items: @items, brands: Brand.all, categories: Category.all, filter: params[:filter] || {} }%>
  </section>

  <section class="content">
    <%= render partial: "items", locals: { items: @items } %>
  </section>
</section>

<script>
$(document).ready(function () {
  $(".filter-form").on("ajax:success", function(event, data){
    $content = $(".content");
    $content.html(data);
  });
});
</script>

app/views/items/new.html.erb
<form action="<%= items_url %>" method="post" enctype="multipart/form-data" class="item-form">

  <% flash[:errors].try(:each) do |error| %>
    <p class="error"><%= error %></p>
  <% end %>

  <%= render partial:"item_fields", locals: { item: @item } %>

  <div class="submit">
    <input type="submit" value="Add new item">
  </div>
</form>

<script>
$(document).ready(function () {
  var photoIndex = 0;

  $(".item-form").on("change", "input[type='file']", function(event){
    photoIndex += 1;
    var inputName = "photos[" + photoIndex + "][image]";
    var li = "<li><input type='file' name=" + inputName + "></li>";
    $(".photo-upload-list").append(li);
  });
});
</script>

app/views/items/show.html.erb
<section class="item-info group">
  <section class="photos-list">
    <ul>
      <% @item.photos.each do |photo| %>
        <li>
          <img src="<%= photo.image.url(:thumb) %>" data-url="<%= photo.image.url(:full) %>">
        </li>
      <% end %>
    </ul>
  </section>

  <section class="photo">
    <img src="<%= @photo.image.url(:full) %>">
  </section>

  <section class="item-details">
    <div class="status-messages">
      <%= render partial: "status_messages" %>
    </div>

    <p>Brand: <%= @item.brand.name %></p>
    <h2><%= @item.name %></h2>
    <% if @item_rating >= 1 %>
      <p>Rating: <%= @item_rating %></p>
    <% else %>
      <p>Rating: This item hasn't been rated</p>
    <% end %>
    <p>Price: $<%= @item.price %></p>
    <p><%= @item.description %></p>
    <% if @item.stock == 0 %>
      <p class="error">Out of Stock</p>
    <% end %>
  </section>

  <section class="item-controls">

    <% if @item.stock > 0 %>
      <%= render partial: "cart_items/new", locals: { item: @item } %>
    <% end %>

    <% if current_user %>
      <%= render partial: "wishlist_items/new", locals: { item: @item, wishlists: @wishlists } %>
    <% end %>
  </section>
</section>

<section class="reviews">
  <h3>Reviews</h3>
  <ul>
    <% @item.reviews.includes(:user).each do |review| %>
      <li>
        <h4>By: <%= review.user.full_name %></h4>
        <h3><%= review.title %></h3>
        <p>Rating: <%= review.rating %></p>
        <p><%= review.body %></p>
      </li>
    <% end %>
  </ul>

  <%= render partial: "reviews/new", locals: { item: @item } if current_user %>
</section>

<script>
$(document).ready(function () {
  $(".item-controls").on("ajax:success", "form", function(event, data){
    $(".status-messages").html(data["status_messages"]);
    this.reset();
  });

  $(".photos-list").on("click", "img", function(event){
    $photoImg = $(".photo").find("img");

    var url = $(this).attr("data-url");
    $photoImg.attr("src", url);
  });
});

</script>