config/routes.rb
ShoppingMania::Application.routes.draw do
  get "auth/facebook/callback" => "sessions#create"

  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:index, :destroy] do
    collection do
      get "activate" => "users#activate"
      get "reset_password" => "users#reset_password"
      post "reset_password" => "users#send_password_token"
      put "reset_password" => "users#update_password"

      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
      resources :carts, only: :show
      resources :orders, only: [:index, :new, :create, :show]
      resources :wishlists, only: [:index, :create, :destroy]
    end
  end

  resources :items do
    collection do
      put "admin/edit" => "items#admin_shortcut"
    end

    resources :cart_items, only: :create
    resources :saved_items, only: :create
    resources :wishlist_items, only: :create
    resources :reviews, only: :create
  end

  resources :cart_items, only: [:update, :destroy]
  resources :saved_items, only: :destroy
  resources :wishlist_items, only: :destroy
  resources :photos, only: :destroy

  root to: "items#index"

end

app/views/layouts/_nav_bar.html.erb
<nav class="top-nav-bar group">
  <nav class="left-nav-links">
    <ul class="group">
      <li><%= link_to "Home", items_url %></li>

      <% if current_user.try(:admin?) %>
        <li><%= link_to "Add New Item", new_item_url %></li>
        <li><%= render partial: "items/admin_search_form" %></li>
      <% end %>
    </ul>
  </nav>

  <nav class="right-nav-links">
    <ul class="group">
      <li><%= link_to "Cart", cart_url(current_user.try(:cart) || "temp") %></li>
      <% if current_user %>
        <li><%= link_to "Account", user_url(current_user) %></li>
        <li><%= button_to "Sign Out", session_url, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_session_url %></li>
      <% end %>
    </ul>
  </nav>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping Mania</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="group">
    <%= image_tag("logo.png", alt: "logo")%>
    <section class="motto">
      <h3>where you can shop to your heart's content without spending money</h3>
    </section>
  </header>

<%= render partial: "layouts/nav_bar" %>

<%= yield %>

</body>
</html>